### ISSUE TITLE
This firmware is too old, so no safety protections!

### ISSUE THREAD

**Issue by mikebdp2** [irishobo/Tronxy-P802MA#1]
If I calculated it correctly _**(you might need to re-check)**_ this Chinese firmware is based on way too old version of Marlin firmware (https://github.com/MarlinFirmware/Marlin) - dated Jun 8, 2014 , commit 6e6e4e2 . Problem is this version is way too old, so it does not have the safety protections like “Thermal Runaway Protection” described below! Here is a plan of what should be done to update this firmware to the latest version:

**1)** Clone the latest **_stable_** version of Marlin firmware and copy it to separate folder
`git clone -b 1.0.x https://github.com/MarlinFirmware/Marlin.git`
**2)** Reset a copy of Marlin repository to commit 6e6e4e2:
`git reset --hard 6e6e4e2`
**3)** using kdiff3 _(or WinMerge for Windows)_, Compare the Chinese firmware with commit 6e6e4e2 to discover all the changes that Chinese developers made to bring compatibility for this printer
**4)** Copy all these compatibility changes made by Chinese developers, to the latest **_stable_** version of Marlin firmware

This will add valuable bugfixes, maybe features, and also safety protections like this one:

/*================== Thermal Runaway Protection ==============================
This is a feature to protect your printer from burn up in flames if it has a thermistor coming off place (this happened to a friend of mine recently and motivated me writing this feature).

The issue: If a thermistor come off, it will read a lower temperature than actual. The system will turn the heater on forever, burning up the filament and anything else around.

After the temperature reaches the target for the first time, this feature will start measuring for how long the current temperature stays below the target
minus _HYSTERESIS (set_temperature – THERMAL_RUNAWAY_PROTECTION_HYSTERESIS).

If it stays longer than _PERIOD, it means the thermistor temperature cannot catch up with the target, so something *may be* wrong. Then, to be on the safe side, the system will he halt.

Bear in mind the count down will just start AFTER the first time the thermistor temperature is over the target, so you will have no problem if your extruder heater takes 2 minutes to hit the target on heating.*/

**Comment by irishobo** [comment]
Yea I was planning on doing this. It took me 2 weeks to get someone from the manufacturer to give me this code.

**Comment by irishobo** [comment]
I have created a new repo for the updated firmware. [https://github.com/irishobo/Tronxy-P802MA-Updated-Firmware](url)

**Comment by mikebdp2** [comment]
@irishobo Please edit your link at your comment above - text is correct, but a link is leading to the wrong place... I have a similar printer model - but it is P802**Y**A _(not P802**M**A)_ and has autoleveling. I ported it to the latest **_stable_** firmware, 1.0.2-2. You might be interested to look on it, friend: https://github.com/mikebdp2/Marlin_1.0.2-2_for_P802YA_8th_gen 
I spent a huge amount of time, carefully analyzing the differences between a "normal" firmware and Chinese firmware and porting them to the latest stable source code. After that I tested this updated firmware - aside from some minor glitches (e.g. UP and DOWN are inverted at one menu) so far its working good and printing OK :+1:
